from hashlib import sha256
from io import BytesIO

from PIL import Image
import pytest

from scripts.audit_real_outputs import audit_project, source_identity_match
from sourceloom import network
from sourceloom.ingest import intake
from sourceloom.materials import bind_web_material_manifest, require_complete_web_materials
from sourceloom.store import Store


def test_rejected_browser_error_keeps_raw_article_and_fetches_its_media(tmp_path,monkeypatch):
    url='https://www.usgs.gov/water-science-school/science/water-cycle'
    prose=('Water moves through the atmosphere, land, and oceans in a continuous cycle. '
           'Evaporation carries water from the surface into the atmosphere, where cooling '
           'forms clouds. Precipitation returns water to rivers, lakes, and groundwater. '
           'Plants also release water vapor, while runoff carries water toward streams. ')
    original=(f'<html><head><title>Water Cycle</title></head><body><main><article>'
              f'<h1>Water Cycle</h1><p>{prose*8}</p><figure><img src="/water-cycle.png" '
              'alt="Water cycle diagram"><figcaption>Water cycle</figcaption></figure>'
              '</article></main></body></html>').encode()
    browser_error=(b'<html><head><title>403 ERROR</title></head><body><h1>403 ERROR</h1>'
                   b'<p>The request could not be satisfied.</p><p>Generated by CloudFront</p>'
                   b'</body></html>')
    image=BytesIO();Image.new('RGB',(3,2),'blue').save(image,'PNG')
    fetched=[]

    def fetch(target,*args):
        fetched.append(target)
        if target==url:return original,'text/html',url
        if target=='https://www.usgs.gov/water-cycle.png':return image.getvalue(),'image/png',target
        raise AssertionError(target)

    def capture(target):
        assert target==url
        candidate=[dict(id='web-object-0001',kind='image',scope='article',figure=True,
                        target='https://cdn.example.invalid/unrelated.png')]
        return browser_error,target,candidate,[('web-captures/error.png',b'capture pixels')]

    monkeypatch.setattr(network,'fetch',fetch)
    import sourceloom.web_capture as web_capture
    monkeypatch.setattr(web_capture,'capture',capture)

    uploads,final,aliases,failures,manifest=network.fetch_bundle(
        url,include_manifest=True,rendered=True)
    bundled=dict(uploads)
    assert final==url
    assert bundled['web-original.bin']==original
    assert bundled['snapshot.html']==original
    assert 'web-captures/error.png' not in bundled
    assert fetched==[url,'https://www.usgs.gov/water-cycle.png']
    assert manifest['rendered'] is None
    assert manifest['rendered_objects']==[]
    assert manifest['source_continuity']['status']=='rejected'
    assert manifest['source_continuity']['reason']=='rendered_error_page'
    assert any(row['reason']=='rendered_snapshot_rejected:rendered_error_page' for row in failures)

    source=intake(Store(tmp_path),uploads,source_url=final,asset_aliases=aliases)
    source['web_snapshot']={'asset_aliases':aliases,'fetch_failures':failures,
                            'scope':'complete supplied HTML body'}
    source=bind_web_material_manifest(source,manifest)
    require_complete_web_materials(source)
    assert source['web_snapshot']['source_continuity']['basis']=='original_response'
    assert source['web_snapshot']['material_summary']['ready_article_figures']==1
    assert any(obj['kind']=='image' and obj.get('resource_id') for obj in source['objects'])


def test_strict_audit_rejects_legacy_snapshot_mismatch_despite_matching_raw_hash():
    url='https://example.test/article'
    original=b'<html><title>Original article</title><main>Substantive original article text.</main></html>'
    mismatch=b'<html><title>403 ERROR</title><body>Generated by CloudFront</body></html>'
    original_sha=sha256(original).hexdigest()
    snapshot_sha=sha256(mismatch).hexdigest()
    inventory={
        'frozen':False,'objects':[],'obligations':[],'resources':[],'unknown':[],
        'source_url':url,
        'originals':[{'name':'web-original.bin','sha256':original_sha,'size':len(original)},
                    {'name':'snapshot.html','sha256':snapshot_sha,'size':len(mismatch)}],
        'web_snapshot':{'material_manifest':[],'material_summary':{
            'article_figures':0,'ready_article_figures':0,'gaps':[]}},
    }
    project={'inventory':inventory,'draft':{'blocks':[]},'production':{},'revision':1}
    expected={'source_key':f'url:{url}|sha256:{original_sha}',
              'canonical_url':url,'sha256':original_sha}

    assert source_identity_match(project,expected)==(
        False,'rendered snapshot differs from original response without continuity metadata')
    audit=audit_project(project,b'',b'',expected)
    failed={row['code'] for row in audit['checks'] if not row['passed']}
    assert 'source_identity_exact' in failed
    assert 'web_snapshot_source_continuity' in failed


def test_article_about_http_errors_keeps_continuity_when_rendered_content_matches():
    from sourceloom.network import _rendered_continuity

    text=('The HTTP 403 error is useful to understand when a CloudFront request is denied. '
          'This article compares the response text with an origin error page and explains '
          'why access denied can appear even when the original document is available. ')*3
    article=(f'<html><head><title>Understanding HTTP 403 Errors</title></head>'
             f'<body><main><article><h1>Understanding HTTP 403 Errors</h1><p>{text}</p>'
             '</article></main></body></html>').encode()
    result=_rendered_continuity(article,article,'https://example.test/article',
                                'https://example.test/article')

    assert result['accepted'] is True
    assert result['reason']=='source_content_continuity'


def test_thin_javascript_shell_retains_unresolved_render_gap(tmp_path,monkeypatch):
    url='https://example.test/dynamic'
    shell=b'<html><head><title>Dynamic article</title></head><body><div id="app"></div></body></html>'
    browser_error=b'<html><title>403 ERROR</title><body>403 ERROR Access Denied</body></html>'
    monkeypatch.setattr(network,'fetch',lambda target,*args:(shell,'text/html',url))
    import sourceloom.web_capture as web_capture
    monkeypatch.setattr(web_capture,'capture',lambda target:(browser_error,url,[],[]))

    uploads,_,_,failures,manifest=network.fetch_bundle(url,include_manifest=True,rendered=True)
    assert dict(uploads)['snapshot.html']==shell
    assert manifest['rendered'] is False
    assert manifest['source_continuity']['status']=='unresolved'
    source=intake(Store(tmp_path),uploads,source_url=url)
    source['web_snapshot']={'fetch_failures':failures,'scope':'complete supplied HTML body'}
    source=bind_web_material_manifest(source,manifest)
    with pytest.raises(ValueError,match='动态网页尚未完成浏览器渲染'):
        require_complete_web_materials(source)


def test_long_navigation_shell_is_not_mistaken_for_static_article(tmp_path,monkeypatch):
    url='https://example.test/portal'
    menu=' '.join(f'Navigation category {index} link' for index in range(50))
    shell=f'<html><title>Portal</title><body><nav>{menu}</nav><div id="app"></div></body></html>'.encode()
    error=b'<html><title>403 ERROR</title><body>403 ERROR Access Denied</body></html>'
    monkeypatch.setattr(network,'fetch',lambda target,*args:(shell,'text/html',url))
    import sourceloom.web_capture as web_capture
    monkeypatch.setattr(web_capture,'capture',lambda target:(error,url,[],[]))

    uploads,_,_,failures,manifest=network.fetch_bundle(url,include_manifest=True,rendered=True)
    source=intake(Store(tmp_path),uploads,source_url=url)
    source['web_snapshot']={'fetch_failures':failures,'scope':'complete supplied HTML body'}
    source=bind_web_material_manifest(source,manifest)

    assert manifest['rendered'] is False
    assert manifest['source_continuity']['status']=='unresolved'
    with pytest.raises(ValueError,match='动态网页尚未完成浏览器渲染'):
        require_complete_web_materials(source)
